[project]
name = "gob"
version = "0.1.0"
dependencies = [
  "numpy==2.1.3",
  "Cython==3.0.11",
  "nlopt==2.8.0",
  "scikit-learn==1.5.1",
  "pyomo==6.8.0",
  "prettytable==3.10.2",
]

[build-system]
requires = ["setuptools", "numpy==2.1.3", "Cython==3.0.11"]
