name: Build optimizers

on:
  push:
    branches: [ "main", "dev"]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-x86-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install libeigen3-dev
          sudo apt-get install python3
          sudo apt-get install -y python3-dev
          python -m pip install --upgrade pip
          python -m pip install build
      
      # Runs a single command using the runners shell
      - name: Install gob
        run: |
          python -m build --sdist --wheel
          pip install . -vvv
          python test.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: linux-artifact
          path: |
           dist/*.whl
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "Release ${{ github.ref }}"
          files: |
            dist/*.whl