name: Build GOB documentation

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Install dependencies
        run: |
          sudo apt install libeigen3-dev
          python -m pip install numpy Cython nlopt prettytable bayesian-optimization gkls

      - name: Build GOB
        run: |
          ./local_compile.sh

      - name: Build documentation
        run: |
          cd docs
          python -m pip install -r requirements.txt
          python gen_doc_files.py
          make html